### ISSUE TITLE
最新の状態でビルドができないのですが、対処方法をご教示ください。

### ISSUE THREAD

**Issue by sho1884** [robo8080/AI_StackChan2#1]
お世話になります。
最新の状態でビルドができないのですが、対処方法をご教示ください。

具体的には、次のエラーが出ます。
src/WakeWord.cpp:5:10: fatal error: esp_ns.h: No such file or directory

少し調べてみると、esp_ns.hは、現在コメントアウトされている以下の中にあるようです。
;platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.4

ただ、これを読み込めば読み込んだで、別のエラーが発生します。

意図されている解決方法をご教示いただければと思います。
お忙しい中を誠に恐縮ですが、よろしくお願いします。

**Comment by robo8080** [comment]
こちらではエラーはでないですね。
.pioフォルダを削除してから再ビルドしてみて下さい。
ちなみにビルしたのはCore2ですよね。
ビルド時の表示は以下の通りでした。
-------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stack-core2.html
PLATFORM: Espressif 32 (6.3.2) > M5Stack Core2
HARDWARE: ESP32 240MHz, 4.31MB RAM, 16MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- M5Unified @ 0.1.7
|-- ESP8266Audio @ 1.9.7
|-- M5Stack-Avatar @ 0.8.6
|-- ServoEasing @ 2.4.1
|-- ESP32Servo @ 0.9.0
|-- ArduinoJson @ 6.21.3
|-- ESP32WebServer @ 1.0.0
|-- SimpleVox @ 0.0.1+sha.f2c589f
|-- SPIFFS @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
|-- SD @ 2.0.0
Building in release mode
Retrieving maximum program size .pio\build\m5stack-core2\firmware.elf
Checking size .pio\build\m5stack-core2\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [          ]   1.4% (used 63908 bytes from 4521984 bytes)
Flash: [===       ]  32.8% (used 2150985 bytes from 6553600 bytes)
=============== [SUCCESS] Took 64.28 seconds ===============

ビルド済みバイナリをM5Burnerに公開しているのでそちらの使用もご検討下さい。

**Comment by sho1884** [comment]
ご対応、ご回答を頂きまして、ありがとうございます。
M5Burnerに公開されているものは既に試しまして、問題ないことは確認できています。
次の段階として、手元でビルド可能にしたいのです。
.pioフォルダは元々ない状態から始めていて、というか、vscodeやplatformio IDEが入っていない完全にクリーンな状態のPC3台でやってみたんですが、どれも同じ結果になってしまっています。
vscodeにplatformio IDEを入れて、platformio.iniのあるフォルダを開いてビルド開始しているだけなんですが、何処か手順が間違っていますでしょうか。
もし何かお気づきのことがあればご教示ください。
あまりお手数をおかけしては申し訳ありませんので、もしも何かお気付きになられたらで結構でございます。
ありがとうございました。

**Comment by robo8080** [comment]
プロジェクトの実体はAI_StackChan2フォルダの下のM5Unified_AI_StackChanフォルダです。ですので、PlatformIOのプロジェクトととしてはM5Unified_AI_StackChanフォルダを指定してください。

**Comment by robo8080** [comment]
もしよくわからない時は、M5Unified_AI_StackChanフォルダをAI_StackChan2フォルダの外へ出してください。

**Comment by sho1884** [comment]
お返事ありがとうございます。
もともとM5Unified_AI_StackChanフォルダを指定していますが、ご助言通り、Cドライブ直下にM5Unified_AI_StackChanフォルダを配置してやってみました。
結果は同じで、以下のようになってしまいます。
framework-arduinoespressif32 @ 3.20011.230801 (2.0.11)のバージョンは違ってしまっているようです。

Processing m5stack-core2 (platform: espressif32; board: m5stack-core2; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stack-core2.html
PLATFORM: Espressif 32 (6.4.0) > M5Stack Core2
HARDWARE: ESP32 240MHz, 4.31MB RAM, 16MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20011.230801 (2.0.11)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- M5Unified @ 0.1.7
|-- ESP8266Audio @ 1.9.7
|-- M5Stack-Avatar @ 0.8.6
|-- ServoEasing @ 2.4.1
|-- ESP32Servo @ 0.9.0
|-- ArduinoJson @ 6.21.3
|-- ESP32WebServer @ 1.0.0
|-- SimpleVox @ 0.0.1+sha.f2c589f
|-- SPIFFS @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
|-- SD @ 2.0.0
Building in release mode
Compiling .pio\build\m5stack-core2\src\Audio.cpp.o
Compiling .pio\build\m5stack-core2\src\AudioFileSourceHTTPSStream.cpp.o
Compiling .pio\build\m5stack-core2\src\AudioWhisper.cpp.o
Compiling .pio\build\m5stack-core2\src\CloudSpeechClient.cpp.o
Compiling .pio\build\m5stack-core2\src\WakeWord.cpp.o
Compiling .pio\build\m5stack-core2\src\WebVoiceVoxTTS.cpp.o
Compiling .pio\build\m5stack-core2\src\Whisper.cpp.o
Compiling .pio\build\m5stack-core2\src\main.cpp.o
src/WakeWord.cpp:5:10: fatal error: esp_ns.h: No such file or directory

****************************************************************
* Looking for esp_ns.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_ns.h"
* Web  > https://registry.platformio.org/search?q=header:esp_ns.h
*
****************************************************************

 #include <esp_ns.h>
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\m5stack-core2\src\WakeWord.cpp.o] Error 1
src/CloudSpeechClient.cpp:9:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_HOST = "speech.googleapis.com";
                            ^~~~~~~~~~~~~~~~~~~~~~~
src/CloudSpeechClient.cpp:11:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_PATH = "/v1/speech:recognize";
                            ^~~~~~~~~~~~~~~~~~~~~~
src/Whisper.cpp:5:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_HOST = "api.openai.com";
                            ^~~~~~~~~~~~~~~~
src/Whisper.cpp:7:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_PATH = "/v1/audio/transcriptions";
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
======================================================================================== [FAILED] Took 27.14 seconds ========================================================================================
Processing esp32-s3-devkitc-1 (platform: espressif32; board: esp32s3box; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Tool Manager: Installing espressif/toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5 has been installed!
Tool Manager: Installing espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: toolchain-riscv32-esp@8.4.0+2021r2-patch5 has been installed!
Library Manager: Installing m5stack/M5Unified @ 0.1.7
Unpacking  [####################################]  100%
Library Manager: M5Unified@0.1.7 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing M5GFX @ >=0.1.7
Unpacking  [####################################]  100%
Library Manager: M5GFX@0.1.9 has been installed!
Library Manager: Installing earlephilhower/ESP8266Audio @ ^1.9.7
Unpacking  [####################################]  100%
Library Manager: ESP8266Audio@1.9.7 has been installed!
Library Manager: Installing meganetaaan/M5Stack-Avatar @ ^0.8.2
Unpacking  [####################################]  100%
Library Manager: M5Stack-Avatar@0.8.6 has been installed!
Library Manager: Installing arminjo/ServoEasing @ ^2.4.0
Unpacking  [####################################]  100%
Library Manager: ServoEasing@2.4.1 has been installed!
Library Manager: Installing madhephaestus/ESP32Servo @ 0.13.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: ESP32Servo@0.13.0 has been installed!
Library Manager: Installing bblanchon/ArduinoJson @ ^6
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.21.3 has been installed!
Library Manager: Installing git+https://github.com/MechaUma/SimpleVox
git version 2.39.1.windows.1
Cloning into 'C:\Users\shouichi.hayashi\.platformio\.cache\tmp\pkg-installing-47qgxkhk'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (20/20), done.
Receiving objects:  60% (14/23)sed 19 (delta 2), pack-reused 0
Receiving objects: 100% (23/23), 19.27 KiB | 6.42 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Library Manager: SimpleVox@0.0.1+sha.f2c589f has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32s3box.html
PLATFORM: Espressif 32 (6.4.0) > Espressif ESP32-S3-Box
HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)PACKAGES:
 - framework-arduinoespressif32 @ 3.20011.230801 (2.0.11)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing ESP32WebServer
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: ESP32WebServer@1.0.0 has been installed!
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- M5Unified @ 0.1.7
|-- ESP8266Audio @ 1.9.7
|-- M5Stack-Avatar @ 0.8.6
|-- ServoEasing @ 2.4.1
|-- ESP32Servo @ 0.13.0
|-- ArduinoJson @ 6.21.3
|-- ESP32WebServer @ 1.0.0
|-- SimpleVox @ 0.0.1+sha.f2c589f
|-- SPIFFS @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
|-- SD @ 2.0.0
Building in release mode
Compiling .pio\build\esp32-s3-devkitc-1\src\Audio.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\AudioFileSourceHTTPSStream.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\AudioWhisper.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\CloudSpeechClient.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\WakeWord.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\WebVoiceVoxTTS.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\Whisper.cpp.o
Compiling .pio\build\esp32-s3-devkitc-1\src\main.cpp.o
src/WakeWord.cpp:5:10: fatal error: esp_ns.h: No such file or directory

****************************************************************
* Looking for esp_ns.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_ns.h"
* Web  > https://registry.platformio.org/search?q=header:esp_ns.h
*
****************************************************************

 #include <esp_ns.h>
          ^~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32-s3-devkitc-1\src\WakeWord.cpp.o] Error 1
src/CloudSpeechClient.cpp:9:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_HOST = "speech.googleapis.com";
                            ^~~~~~~~~~~~~~~~~~~~~~~
src/CloudSpeechClient.cpp:11:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_PATH = "/v1/speech:recognize";
                            ^~~~~~~~~~~~~~~~~~~~~~
src/Whisper.cpp:5:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_HOST = "api.openai.com";
                            ^~~~~~~~~~~~~~~~
src/Whisper.cpp:7:28: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 constexpr char* API_PATH = "/v1/audio/transcriptions";
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
======================================================================================= [FAILED] Took 186.13 seconds =======================================================================================

Environment         Status    Duration
------------------  --------  ------------
m5stack-core2       FAILED    00:00:27.136
esp32-s3-devkitc-1  FAILED    00:03:06.128
=================================================================================== 2 failed, 0 succeeded in 00:03:33.264 ===================================================================================

**Comment by robo8080** [comment]
ログを見るとespressif32のバージョンが違うようなので
platformio.iniの12行目、35行目を以下にしてみては？

platform = espressif32@6.3.2

**Comment by sho1884** [comment]
ご対応、ご連絡いただきまして、ありがとうございます。
無事、ビルドもアップロードも上手くいきました。

素人の私は先にいただいた情報からplatform = espressif32@2.0.9などと試して、うまくいかずに悩んでおりました。
未だ、なんで@6.3.2なのか分かっていないのですが、とりあえず動いてとても助かりました。
ありがとうございました。

**Comment by robo8080** [comment]
上手くいってよかったです。
