### ISSUE TITLE
ソースコード内のAPIキーについて

### ISSUE THREAD

**Issue by ronron-gh** [robo8080/AI_StackChan2#5]
お世話になっております。
私のリポジトリに次のような連絡がありました。

> WebVoiceVoxTTS.cppにsk-**のキーがコメントアウトされています。
> ダミーとは思いますが、念のため連絡しておきます。

確認したところ、ロボさんのソフトから引き継いだファイルでした。WebVoiceVoxTTS.cppの73行目と223行目です。
もし有効なAPIキーでしたら、無効化して新たなキーを取得するなどの対策が必要と思いましたので、念のためご連絡いたしました。

**Comment by robo8080** [comment]
無効なAPIキーです。
ご連絡ありがとうございます。
